version: '3'
services:
  backend-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=backend_db
      - POSTGRES_HOST=postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "backend"
      POSTGRES_PASSWORD: "backend"
      POSTGRES_DB: "backend_db"
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
